/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as adminLayoutRouteImport } from './routes/(admin)/_layout'
import { Route as adminLayoutDashboardRouteImport } from './routes/(admin)/_layout/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDashboardListRouteImport } from './routes/api/dashboard/list'
import { Route as ApiDocumentsCategoriesRouteImport } from './routes/api/documents/categories'
import { Route as ApiDocumentsCreateRouteImport } from './routes/api/documents/create'
import { Route as ApiDocumentsGenerateUrlRouteImport } from './routes/api/documents/generate-url'
import { Route as ApiDocumentsListRouteImport } from './routes/api/documents/list'
import { Route as ApiDocumentsTypesRouteImport } from './routes/api/documents/types'
import { Route as ApiUsersCreateRouteImport } from './routes/api/users/create'
import { Route as ApiUsersEditRouteImport } from './routes/api/users/edit'
import { Route as ApiUsersGetUserRouteImport } from './routes/api/users/get-user'
import { Route as ApiUsersListRouteImport } from './routes/api/users/list'
import { Route as ApiUsersResetPasswordRouteImport } from './routes/api/users/reset-password'
import { Route as ApiUsersUpdatePasswordRouteImport } from './routes/api/users/update-password'
import { Route as adminLayoutDocumentosIndexRouteImport } from './routes/(admin)/_layout/documentos/index'
import { Route as adminLayoutDocumentosNovo_documentoRouteImport } from './routes/(admin)/_layout/documentos/novo_documento'
import { Route as adminLayoutUsuariosLayoutRouteImport } from './routes/(admin)/_layout/usuarios/_layout'
import { Route as adminLayoutUsuariosLayoutIndexRouteImport } from './routes/(admin)/_layout/usuarios/_layout/index'
import { Route as adminLayoutUsuariosLayoutNovo_usuarioRouteImport } from './routes/(admin)/_layout/usuarios/_layout/novo_usuario'
import { Route as adminLayoutUsuariosLayoutEditar_usuarioUserIdRouteImport } from './routes/(admin)/_layout/usuarios/_layout/editar_usuario/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutDashboardRoute = adminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => adminLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardListRoute = ApiDashboardListRouteImport.update({
  id: '/api/dashboard/list',
  path: '/api/dashboard/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsCategoriesRoute = ApiDocumentsCategoriesRouteImport.update({
  id: '/api/documents/categories',
  path: '/api/documents/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsCreateRoute = ApiDocumentsCreateRouteImport.update({
  id: '/api/documents/create',
  path: '/api/documents/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsGenerateUrlRoute = ApiDocumentsGenerateUrlRouteImport.update({
  id: '/api/documents/generate-url',
  path: '/api/documents/generate-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsListRoute = ApiDocumentsListRouteImport.update({
  id: '/api/documents/list',
  path: '/api/documents/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsTypesRoute = ApiDocumentsTypesRouteImport.update({
  id: '/api/documents/types',
  path: '/api/documents/types',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersCreateRoute = ApiUsersCreateRouteImport.update({
  id: '/api/users/create',
  path: '/api/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersEditRoute = ApiUsersEditRouteImport.update({
  id: '/api/users/edit',
  path: '/api/users/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersGetUserRoute = ApiUsersGetUserRouteImport.update({
  id: '/api/users/get-user',
  path: '/api/users/get-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersListRoute = ApiUsersListRouteImport.update({
  id: '/api/users/list',
  path: '/api/users/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersResetPasswordRoute = ApiUsersResetPasswordRouteImport.update({
  id: '/api/users/reset-password',
  path: '/api/users/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUpdatePasswordRoute = ApiUsersUpdatePasswordRouteImport.update({
  id: '/api/users/update-password',
  path: '/api/users/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutDocumentosIndexRoute =
  adminLayoutDocumentosIndexRouteImport.update({
    id: '/documentos/',
    path: '/documentos/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLayoutDocumentosNovo_documentoRoute =
  adminLayoutDocumentosNovo_documentoRouteImport.update({
    id: '/documentos/novo_documento',
    path: '/documentos/novo_documento',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLayoutUsuariosLayoutRoute =
  adminLayoutUsuariosLayoutRouteImport.update({
    id: '/usuarios/_layout',
    path: '/usuarios',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLayoutUsuariosLayoutIndexRoute =
  adminLayoutUsuariosLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminLayoutUsuariosLayoutRoute,
  } as any)
const adminLayoutUsuariosLayoutNovo_usuarioRoute =
  adminLayoutUsuariosLayoutNovo_usuarioRouteImport.update({
    id: '/novo_usuario',
    path: '/novo_usuario',
    getParentRoute: () => adminLayoutUsuariosLayoutRoute,
  } as any)
const adminLayoutUsuariosLayoutEditar_usuarioUserIdRoute =
  adminLayoutUsuariosLayoutEditar_usuarioUserIdRouteImport.update({
    id: '/editar_usuario/$userId',
    path: '/editar_usuario/$userId',
    getParentRoute: () => adminLayoutUsuariosLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/dashboard': typeof adminLayoutDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dashboard/list': typeof ApiDashboardListRoute
  '/api/documents/categories': typeof ApiDocumentsCategoriesRoute
  '/api/documents/create': typeof ApiDocumentsCreateRoute
  '/api/documents/generate-url': typeof ApiDocumentsGenerateUrlRoute
  '/api/documents/list': typeof ApiDocumentsListRoute
  '/api/documents/types': typeof ApiDocumentsTypesRoute
  '/api/users/create': typeof ApiUsersCreateRoute
  '/api/users/edit': typeof ApiUsersEditRoute
  '/api/users/get-user': typeof ApiUsersGetUserRoute
  '/api/users/list': typeof ApiUsersListRoute
  '/api/users/reset-password': typeof ApiUsersResetPasswordRoute
  '/api/users/update-password': typeof ApiUsersUpdatePasswordRoute
  '/documentos/novo_documento': typeof adminLayoutDocumentosNovo_documentoRoute
  '/usuarios': typeof adminLayoutUsuariosLayoutRouteWithChildren
  '/documentos/': typeof adminLayoutDocumentosIndexRoute
  '/usuarios/novo_usuario': typeof adminLayoutUsuariosLayoutNovo_usuarioRoute
  '/usuarios/': typeof adminLayoutUsuariosLayoutIndexRoute
  '/usuarios/editar_usuario/$userId': typeof adminLayoutUsuariosLayoutEditar_usuarioUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/dashboard': typeof adminLayoutDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dashboard/list': typeof ApiDashboardListRoute
  '/api/documents/categories': typeof ApiDocumentsCategoriesRoute
  '/api/documents/create': typeof ApiDocumentsCreateRoute
  '/api/documents/generate-url': typeof ApiDocumentsGenerateUrlRoute
  '/api/documents/list': typeof ApiDocumentsListRoute
  '/api/documents/types': typeof ApiDocumentsTypesRoute
  '/api/users/create': typeof ApiUsersCreateRoute
  '/api/users/edit': typeof ApiUsersEditRoute
  '/api/users/get-user': typeof ApiUsersGetUserRoute
  '/api/users/list': typeof ApiUsersListRoute
  '/api/users/reset-password': typeof ApiUsersResetPasswordRoute
  '/api/users/update-password': typeof ApiUsersUpdatePasswordRoute
  '/documentos/novo_documento': typeof adminLayoutDocumentosNovo_documentoRoute
  '/documentos': typeof adminLayoutDocumentosIndexRoute
  '/usuarios/novo_usuario': typeof adminLayoutUsuariosLayoutNovo_usuarioRoute
  '/usuarios': typeof adminLayoutUsuariosLayoutIndexRoute
  '/usuarios/editar_usuario/$userId': typeof adminLayoutUsuariosLayoutEditar_usuarioUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/(admin)/_layout': typeof adminLayoutRouteWithChildren
  '/(admin)/_layout/dashboard': typeof adminLayoutDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dashboard/list': typeof ApiDashboardListRoute
  '/api/documents/categories': typeof ApiDocumentsCategoriesRoute
  '/api/documents/create': typeof ApiDocumentsCreateRoute
  '/api/documents/generate-url': typeof ApiDocumentsGenerateUrlRoute
  '/api/documents/list': typeof ApiDocumentsListRoute
  '/api/documents/types': typeof ApiDocumentsTypesRoute
  '/api/users/create': typeof ApiUsersCreateRoute
  '/api/users/edit': typeof ApiUsersEditRoute
  '/api/users/get-user': typeof ApiUsersGetUserRoute
  '/api/users/list': typeof ApiUsersListRoute
  '/api/users/reset-password': typeof ApiUsersResetPasswordRoute
  '/api/users/update-password': typeof ApiUsersUpdatePasswordRoute
  '/(admin)/_layout/documentos/novo_documento': typeof adminLayoutDocumentosNovo_documentoRoute
  '/(admin)/_layout/usuarios/_layout': typeof adminLayoutUsuariosLayoutRouteWithChildren
  '/(admin)/_layout/documentos/': typeof adminLayoutDocumentosIndexRoute
  '/(admin)/_layout/usuarios/_layout/novo_usuario': typeof adminLayoutUsuariosLayoutNovo_usuarioRoute
  '/(admin)/_layout/usuarios/_layout/': typeof adminLayoutUsuariosLayoutIndexRoute
  '/(admin)/_layout/usuarios/_layout/editar_usuario/$userId': typeof adminLayoutUsuariosLayoutEditar_usuarioUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/dashboard/list'
    | '/api/documents/categories'
    | '/api/documents/create'
    | '/api/documents/generate-url'
    | '/api/documents/list'
    | '/api/documents/types'
    | '/api/users/create'
    | '/api/users/edit'
    | '/api/users/get-user'
    | '/api/users/list'
    | '/api/users/reset-password'
    | '/api/users/update-password'
    | '/documentos/novo_documento'
    | '/usuarios'
    | '/documentos/'
    | '/usuarios/novo_usuario'
    | '/usuarios/'
    | '/usuarios/editar_usuario/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/dashboard/list'
    | '/api/documents/categories'
    | '/api/documents/create'
    | '/api/documents/generate-url'
    | '/api/documents/list'
    | '/api/documents/types'
    | '/api/users/create'
    | '/api/users/edit'
    | '/api/users/get-user'
    | '/api/users/list'
    | '/api/users/reset-password'
    | '/api/users/update-password'
    | '/documentos/novo_documento'
    | '/documentos'
    | '/usuarios/novo_usuario'
    | '/usuarios'
    | '/usuarios/editar_usuario/$userId'
  id:
    | '__root__'
    | '/'
    | '/alterar-senha'
    | '/(admin)/_layout'
    | '/(admin)/_layout/dashboard'
    | '/api/auth/$'
    | '/api/dashboard/list'
    | '/api/documents/categories'
    | '/api/documents/create'
    | '/api/documents/generate-url'
    | '/api/documents/list'
    | '/api/documents/types'
    | '/api/users/create'
    | '/api/users/edit'
    | '/api/users/get-user'
    | '/api/users/list'
    | '/api/users/reset-password'
    | '/api/users/update-password'
    | '/(admin)/_layout/documentos/novo_documento'
    | '/(admin)/_layout/usuarios/_layout'
    | '/(admin)/_layout/documentos/'
    | '/(admin)/_layout/usuarios/_layout/novo_usuario'
    | '/(admin)/_layout/usuarios/_layout/'
    | '/(admin)/_layout/usuarios/_layout/editar_usuario/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDashboardListRoute: typeof ApiDashboardListRoute
  ApiDocumentsCategoriesRoute: typeof ApiDocumentsCategoriesRoute
  ApiDocumentsCreateRoute: typeof ApiDocumentsCreateRoute
  ApiDocumentsGenerateUrlRoute: typeof ApiDocumentsGenerateUrlRoute
  ApiDocumentsListRoute: typeof ApiDocumentsListRoute
  ApiDocumentsTypesRoute: typeof ApiDocumentsTypesRoute
  ApiUsersCreateRoute: typeof ApiUsersCreateRoute
  ApiUsersEditRoute: typeof ApiUsersEditRoute
  ApiUsersGetUserRoute: typeof ApiUsersGetUserRoute
  ApiUsersListRoute: typeof ApiUsersListRoute
  ApiUsersResetPasswordRoute: typeof ApiUsersResetPasswordRoute
  ApiUsersUpdatePasswordRoute: typeof ApiUsersUpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout': {
      id: '/(admin)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout/dashboard': {
      id: '/(admin)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminLayoutDashboardRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/list': {
      id: '/api/dashboard/list'
      path: '/api/dashboard/list'
      fullPath: '/api/dashboard/list'
      preLoaderRoute: typeof ApiDashboardListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/categories': {
      id: '/api/documents/categories'
      path: '/api/documents/categories'
      fullPath: '/api/documents/categories'
      preLoaderRoute: typeof ApiDocumentsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/create': {
      id: '/api/documents/create'
      path: '/api/documents/create'
      fullPath: '/api/documents/create'
      preLoaderRoute: typeof ApiDocumentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/generate-url': {
      id: '/api/documents/generate-url'
      path: '/api/documents/generate-url'
      fullPath: '/api/documents/generate-url'
      preLoaderRoute: typeof ApiDocumentsGenerateUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/list': {
      id: '/api/documents/list'
      path: '/api/documents/list'
      fullPath: '/api/documents/list'
      preLoaderRoute: typeof ApiDocumentsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/types': {
      id: '/api/documents/types'
      path: '/api/documents/types'
      fullPath: '/api/documents/types'
      preLoaderRoute: typeof ApiDocumentsTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/create': {
      id: '/api/users/create'
      path: '/api/users/create'
      fullPath: '/api/users/create'
      preLoaderRoute: typeof ApiUsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/edit': {
      id: '/api/users/edit'
      path: '/api/users/edit'
      fullPath: '/api/users/edit'
      preLoaderRoute: typeof ApiUsersEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/get-user': {
      id: '/api/users/get-user'
      path: '/api/users/get-user'
      fullPath: '/api/users/get-user'
      preLoaderRoute: typeof ApiUsersGetUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/list': {
      id: '/api/users/list'
      path: '/api/users/list'
      fullPath: '/api/users/list'
      preLoaderRoute: typeof ApiUsersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/reset-password': {
      id: '/api/users/reset-password'
      path: '/api/users/reset-password'
      fullPath: '/api/users/reset-password'
      preLoaderRoute: typeof ApiUsersResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/update-password': {
      id: '/api/users/update-password'
      path: '/api/users/update-password'
      fullPath: '/api/users/update-password'
      preLoaderRoute: typeof ApiUsersUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout/documentos/': {
      id: '/(admin)/_layout/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof adminLayoutDocumentosIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/_layout/documentos/novo_documento': {
      id: '/(admin)/_layout/documentos/novo_documento'
      path: '/documentos/novo_documento'
      fullPath: '/documentos/novo_documento'
      preLoaderRoute: typeof adminLayoutDocumentosNovo_documentoRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/_layout/usuarios/_layout': {
      id: '/(admin)/_layout/usuarios/_layout'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof adminLayoutUsuariosLayoutRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/_layout/usuarios/_layout/': {
      id: '/(admin)/_layout/usuarios/_layout/'
      path: '/'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof adminLayoutUsuariosLayoutIndexRouteImport
      parentRoute: typeof adminLayoutUsuariosLayoutRoute
    }
    '/(admin)/_layout/usuarios/_layout/novo_usuario': {
      id: '/(admin)/_layout/usuarios/_layout/novo_usuario'
      path: '/novo_usuario'
      fullPath: '/usuarios/novo_usuario'
      preLoaderRoute: typeof adminLayoutUsuariosLayoutNovo_usuarioRouteImport
      parentRoute: typeof adminLayoutUsuariosLayoutRoute
    }
    '/(admin)/_layout/usuarios/_layout/editar_usuario/$userId': {
      id: '/(admin)/_layout/usuarios/_layout/editar_usuario/$userId'
      path: '/editar_usuario/$userId'
      fullPath: '/usuarios/editar_usuario/$userId'
      preLoaderRoute: typeof adminLayoutUsuariosLayoutEditar_usuarioUserIdRouteImport
      parentRoute: typeof adminLayoutUsuariosLayoutRoute
    }
  }
}

interface adminLayoutUsuariosLayoutRouteChildren {
  adminLayoutUsuariosLayoutNovo_usuarioRoute: typeof adminLayoutUsuariosLayoutNovo_usuarioRoute
  adminLayoutUsuariosLayoutIndexRoute: typeof adminLayoutUsuariosLayoutIndexRoute
  adminLayoutUsuariosLayoutEditar_usuarioUserIdRoute: typeof adminLayoutUsuariosLayoutEditar_usuarioUserIdRoute
}

const adminLayoutUsuariosLayoutRouteChildren: adminLayoutUsuariosLayoutRouteChildren =
  {
    adminLayoutUsuariosLayoutNovo_usuarioRoute:
      adminLayoutUsuariosLayoutNovo_usuarioRoute,
    adminLayoutUsuariosLayoutIndexRoute: adminLayoutUsuariosLayoutIndexRoute,
    adminLayoutUsuariosLayoutEditar_usuarioUserIdRoute:
      adminLayoutUsuariosLayoutEditar_usuarioUserIdRoute,
  }

const adminLayoutUsuariosLayoutRouteWithChildren =
  adminLayoutUsuariosLayoutRoute._addFileChildren(
    adminLayoutUsuariosLayoutRouteChildren,
  )

interface adminLayoutRouteChildren {
  adminLayoutDashboardRoute: typeof adminLayoutDashboardRoute
  adminLayoutDocumentosNovo_documentoRoute: typeof adminLayoutDocumentosNovo_documentoRoute
  adminLayoutUsuariosLayoutRoute: typeof adminLayoutUsuariosLayoutRouteWithChildren
  adminLayoutDocumentosIndexRoute: typeof adminLayoutDocumentosIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminLayoutDashboardRoute: adminLayoutDashboardRoute,
  adminLayoutDocumentosNovo_documentoRoute:
    adminLayoutDocumentosNovo_documentoRoute,
  adminLayoutUsuariosLayoutRoute: adminLayoutUsuariosLayoutRouteWithChildren,
  adminLayoutDocumentosIndexRoute: adminLayoutDocumentosIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDashboardListRoute: ApiDashboardListRoute,
  ApiDocumentsCategoriesRoute: ApiDocumentsCategoriesRoute,
  ApiDocumentsCreateRoute: ApiDocumentsCreateRoute,
  ApiDocumentsGenerateUrlRoute: ApiDocumentsGenerateUrlRoute,
  ApiDocumentsListRoute: ApiDocumentsListRoute,
  ApiDocumentsTypesRoute: ApiDocumentsTypesRoute,
  ApiUsersCreateRoute: ApiUsersCreateRoute,
  ApiUsersEditRoute: ApiUsersEditRoute,
  ApiUsersGetUserRoute: ApiUsersGetUserRoute,
  ApiUsersListRoute: ApiUsersListRoute,
  ApiUsersResetPasswordRoute: ApiUsersResetPasswordRoute,
  ApiUsersUpdatePasswordRoute: ApiUsersUpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
