/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as adminLayoutRouteImport } from './routes/(admin)/_layout'
import { Route as adminLayoutDashboardRouteImport } from './routes/(admin)/_layout/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as adminLayoutDocumentosIndexRouteImport } from './routes/(admin)/_layout/documentos/index'
import { Route as adminLayoutDocumentosNovo_documentoRouteImport } from './routes/(admin)/_layout/documentos/novo_documento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutDashboardRoute = adminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => adminLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutDocumentosIndexRoute =
  adminLayoutDocumentosIndexRouteImport.update({
    id: '/documentos/',
    path: '/documentos/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLayoutDocumentosNovo_documentoRoute =
  adminLayoutDocumentosNovo_documentoRouteImport.update({
    id: '/documentos/novo_documento',
    path: '/documentos/novo_documento',
    getParentRoute: () => adminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof adminLayoutDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/documentos/novo_documento': typeof adminLayoutDocumentosNovo_documentoRoute
  '/documentos/': typeof adminLayoutDocumentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof adminLayoutDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/documentos/novo_documento': typeof adminLayoutDocumentosNovo_documentoRoute
  '/documentos': typeof adminLayoutDocumentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)/_layout': typeof adminLayoutRouteWithChildren
  '/(admin)/_layout/dashboard': typeof adminLayoutDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(admin)/_layout/documentos/novo_documento': typeof adminLayoutDocumentosNovo_documentoRoute
  '/(admin)/_layout/documentos/': typeof adminLayoutDocumentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/documentos/novo_documento'
    | '/documentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/documentos/novo_documento'
    | '/documentos'
  id:
    | '__root__'
    | '/'
    | '/(admin)/_layout'
    | '/(admin)/_layout/dashboard'
    | '/api/auth/$'
    | '/(admin)/_layout/documentos/novo_documento'
    | '/(admin)/_layout/documentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout': {
      id: '/(admin)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout/dashboard': {
      id: '/(admin)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminLayoutDashboardRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout/documentos/': {
      id: '/(admin)/_layout/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof adminLayoutDocumentosIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/_layout/documentos/novo_documento': {
      id: '/(admin)/_layout/documentos/novo_documento'
      path: '/documentos/novo_documento'
      fullPath: '/documentos/novo_documento'
      preLoaderRoute: typeof adminLayoutDocumentosNovo_documentoRouteImport
      parentRoute: typeof adminLayoutRoute
    }
  }
}

interface adminLayoutRouteChildren {
  adminLayoutDashboardRoute: typeof adminLayoutDashboardRoute
  adminLayoutDocumentosNovo_documentoRoute: typeof adminLayoutDocumentosNovo_documentoRoute
  adminLayoutDocumentosIndexRoute: typeof adminLayoutDocumentosIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminLayoutDashboardRoute: adminLayoutDashboardRoute,
  adminLayoutDocumentosNovo_documentoRoute:
    adminLayoutDocumentosNovo_documentoRoute,
  adminLayoutDocumentosIndexRoute: adminLayoutDocumentosIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
