/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as adminLayoutRouteImport } from './routes/(admin)/_layout'
import { Route as adminLayoutDashboardRouteImport } from './routes/(admin)/_layout/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDocumentsCategoriesRouteImport } from './routes/api/documents/categories'
import { Route as ApiDocumentsTypesRouteImport } from './routes/api/documents/types'
import { Route as ApiUsersListRouteImport } from './routes/api/users/list'
import { Route as adminLayoutDocumentosIndexRouteImport } from './routes/(admin)/_layout/documentos/index'
import { Route as adminLayoutDocumentosNovo_documentoRouteImport } from './routes/(admin)/_layout/documentos/novo_documento'
import { Route as adminLayoutUsuariosIndexRouteImport } from './routes/(admin)/_layout/usuarios/index'
import { Route as adminLayoutUsuariosNovo_usuarioRouteImport } from './routes/(admin)/_layout/usuarios/novo_usuario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutDashboardRoute = adminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => adminLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsCategoriesRoute = ApiDocumentsCategoriesRouteImport.update({
  id: '/api/documents/categories',
  path: '/api/documents/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsTypesRoute = ApiDocumentsTypesRouteImport.update({
  id: '/api/documents/types',
  path: '/api/documents/types',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersListRoute = ApiUsersListRouteImport.update({
  id: '/api/users/list',
  path: '/api/users/list',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutDocumentosIndexRoute =
  adminLayoutDocumentosIndexRouteImport.update({
    id: '/documentos/',
    path: '/documentos/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLayoutDocumentosNovo_documentoRoute =
  adminLayoutDocumentosNovo_documentoRouteImport.update({
    id: '/documentos/novo_documento',
    path: '/documentos/novo_documento',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLayoutUsuariosIndexRoute =
  adminLayoutUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLayoutUsuariosNovo_usuarioRoute =
  adminLayoutUsuariosNovo_usuarioRouteImport.update({
    id: '/usuarios/novo_usuario',
    path: '/usuarios/novo_usuario',
    getParentRoute: () => adminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof adminLayoutDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/categories': typeof ApiDocumentsCategoriesRoute
  '/api/documents/types': typeof ApiDocumentsTypesRoute
  '/api/users/list': typeof ApiUsersListRoute
  '/documentos/novo_documento': typeof adminLayoutDocumentosNovo_documentoRoute
  '/usuarios/novo_usuario': typeof adminLayoutUsuariosNovo_usuarioRoute
  '/documentos/': typeof adminLayoutDocumentosIndexRoute
  '/usuarios/': typeof adminLayoutUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof adminLayoutDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/categories': typeof ApiDocumentsCategoriesRoute
  '/api/documents/types': typeof ApiDocumentsTypesRoute
  '/api/users/list': typeof ApiUsersListRoute
  '/documentos/novo_documento': typeof adminLayoutDocumentosNovo_documentoRoute
  '/usuarios/novo_usuario': typeof adminLayoutUsuariosNovo_usuarioRoute
  '/documentos': typeof adminLayoutDocumentosIndexRoute
  '/usuarios': typeof adminLayoutUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)/_layout': typeof adminLayoutRouteWithChildren
  '/(admin)/_layout/dashboard': typeof adminLayoutDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/categories': typeof ApiDocumentsCategoriesRoute
  '/api/documents/types': typeof ApiDocumentsTypesRoute
  '/api/users/list': typeof ApiUsersListRoute
  '/(admin)/_layout/documentos/novo_documento': typeof adminLayoutDocumentosNovo_documentoRoute
  '/(admin)/_layout/usuarios/novo_usuario': typeof adminLayoutUsuariosNovo_usuarioRoute
  '/(admin)/_layout/documentos/': typeof adminLayoutDocumentosIndexRoute
  '/(admin)/_layout/usuarios/': typeof adminLayoutUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/documents/categories'
    | '/api/documents/types'
    | '/api/users/list'
    | '/documentos/novo_documento'
    | '/usuarios/novo_usuario'
    | '/documentos/'
    | '/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/documents/categories'
    | '/api/documents/types'
    | '/api/users/list'
    | '/documentos/novo_documento'
    | '/usuarios/novo_usuario'
    | '/documentos'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/(admin)/_layout'
    | '/(admin)/_layout/dashboard'
    | '/api/auth/$'
    | '/api/documents/categories'
    | '/api/documents/types'
    | '/api/users/list'
    | '/(admin)/_layout/documentos/novo_documento'
    | '/(admin)/_layout/usuarios/novo_usuario'
    | '/(admin)/_layout/documentos/'
    | '/(admin)/_layout/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsCategoriesRoute: typeof ApiDocumentsCategoriesRoute
  ApiDocumentsTypesRoute: typeof ApiDocumentsTypesRoute
  ApiUsersListRoute: typeof ApiUsersListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout': {
      id: '/(admin)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout/dashboard': {
      id: '/(admin)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminLayoutDashboardRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/categories': {
      id: '/api/documents/categories'
      path: '/api/documents/categories'
      fullPath: '/api/documents/categories'
      preLoaderRoute: typeof ApiDocumentsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/types': {
      id: '/api/documents/types'
      path: '/api/documents/types'
      fullPath: '/api/documents/types'
      preLoaderRoute: typeof ApiDocumentsTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/list': {
      id: '/api/users/list'
      path: '/api/users/list'
      fullPath: '/api/users/list'
      preLoaderRoute: typeof ApiUsersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_layout/documentos/': {
      id: '/(admin)/_layout/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof adminLayoutDocumentosIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/_layout/documentos/novo_documento': {
      id: '/(admin)/_layout/documentos/novo_documento'
      path: '/documentos/novo_documento'
      fullPath: '/documentos/novo_documento'
      preLoaderRoute: typeof adminLayoutDocumentosNovo_documentoRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/_layout/usuarios/': {
      id: '/(admin)/_layout/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof adminLayoutUsuariosIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/_layout/usuarios/novo_usuario': {
      id: '/(admin)/_layout/usuarios/novo_usuario'
      path: '/usuarios/novo_usuario'
      fullPath: '/usuarios/novo_usuario'
      preLoaderRoute: typeof adminLayoutUsuariosNovo_usuarioRouteImport
      parentRoute: typeof adminLayoutRoute
    }
  }
}

interface adminLayoutRouteChildren {
  adminLayoutDashboardRoute: typeof adminLayoutDashboardRoute
  adminLayoutDocumentosNovo_documentoRoute: typeof adminLayoutDocumentosNovo_documentoRoute
  adminLayoutUsuariosNovo_usuarioRoute: typeof adminLayoutUsuariosNovo_usuarioRoute
  adminLayoutDocumentosIndexRoute: typeof adminLayoutDocumentosIndexRoute
  adminLayoutUsuariosIndexRoute: typeof adminLayoutUsuariosIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminLayoutDashboardRoute: adminLayoutDashboardRoute,
  adminLayoutDocumentosNovo_documentoRoute:
    adminLayoutDocumentosNovo_documentoRoute,
  adminLayoutUsuariosNovo_usuarioRoute: adminLayoutUsuariosNovo_usuarioRoute,
  adminLayoutDocumentosIndexRoute: adminLayoutDocumentosIndexRoute,
  adminLayoutUsuariosIndexRoute: adminLayoutUsuariosIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsCategoriesRoute: ApiDocumentsCategoriesRoute,
  ApiDocumentsTypesRoute: ApiDocumentsTypesRoute,
  ApiUsersListRoute: ApiUsersListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
